const state={me:null,bots:[]};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function toast(msg,error=false){const t=$('#toast');t.textContent=msg;t.className='toast show'+(error?' error':'');clearTimeout(t._x);t._x=setTimeout(()=>t.className='toast',2800)}
function apiBase(){return String(window.ZBC_CONFIG?.API_BASE||'').replace(/\/$/,'')}
function token(){return sessionStorage.getItem('zbc_token')||localStorage.getItem('zbc_token')||''}
async function api(url,opts={}){const headers={'Content-Type':'application/json',...(opts.headers||{})};if(token())headers.Authorization=`Bearer ${token()}`;const r=await fetch(apiBase()+url,{headers,...opts});let data;try{data=await r.json()}catch{data={detail:await r.text()}}if(!r.ok)throw new Error(data.detail||`HTTP ${r.status}`);return data}
function log(s){const el=$('#liveLog');if(el)el.textContent=`[${new Date().toLocaleTimeString()}] ${s}\n`+el.textContent}
function setView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('#pageTitle').textContent=({overview:'Overview',bots:'Bots',commands:'Command Center',servers:'Servers',logs:'Live Logs',analytics:'Analytics',scheduler:'Scheduler',errors:'Errors',updates:'Updates',permissions:'Permissions',audit:'Audit Log',developer:'Developer',settings:'Settings'})[name]||name;localStorage.setItem('zbc_view',name);if(name==='audit')loadAudit();if(name==='errors')loadErrors();if(name==='scheduler')loadSchedules();if(name==='servers')loadServers();if(name==='logs')loadLogs()}
function applyRole(){const r=state.me.role;$('#username').textContent=state.me.username;$('#role').textContent=r;$('#avatar').src=state.me.avatar||'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="64" height="64"%3E%3Crect width="64" height="64" rx="14" fill="%23121720"/%3E%3Ctext x="32" y="40" text-anchor="middle" font-size="24" fill="white"%3EZ%3C/text%3E%3C/svg%3E';if(r==='staff'){$$('.admin-only,.owner-only,[data-view="overview"]').forEach(x=>x.classList.add('hidden'));$('#view-overview')?.classList.add('hidden')}else if(r==='admin')$$('.owner-only').forEach(x=>x.classList.add('hidden'))}
function botCard(b){const online=b.status==='online',staff=state.me.role==='staff';return `<article class="bot-card glass spotlight tilt"><div class="bot-head"><div class="bot-id"><div class="bot-icon">🤖</div><div><b>${esc(b.name)}</b><small>${esc(b.bot_id)}</small></div></div><span class="status-pill ${online?'online':'offline'}">${online?'ONLINE':'OFFLINE'}</span></div>${staff?'':`<div class="bot-metrics"><div class="metric"><small>PING</small><b>${Math.round(b.ping_ms||0)} ms</b></div><div class="metric"><small>UPTIME</small><b>${formatUptime(b.uptime_seconds||0)}</b></div><div class="metric"><small>GUILDS</small><b>${b.guilds||0}</b></div></div><div class="bot-actions admin-only"><button class="btn ghost" onclick="life('${esc(b.bot_id)}','start')">Start</button><button class="btn ghost" onclick="life('${esc(b.bot_id)}','restart')">Restart</button><button class="btn ghost" onclick="life('${esc(b.bot_id)}','stop')">Stop</button></div>`}</article>`}
function formatUptime(s){if(!s)return'—';const d=Math.floor(s/86400),h=Math.floor(s%86400/3600),m=Math.floor(s%3600/60);return d?`${d}d ${h}h`:h?`${h}h ${m}m`:`${m}m`}
function renderBots(){const b=state.bots,online=b.filter(x=>x.status==='online').length,staff=state.me.role==='staff',guilds=b.reduce((a,x)=>a+(x.guilds||0),0),commands=b.reduce((a,x)=>a+(x.commands||0),0);if(staff){$('#botTable').innerHTML=`<table><thead><tr><th>BOT</th><th>STATUS</th></tr></thead><tbody>${b.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td><span class="status-pill ${x.status==='online'?'online':'offline'}">${x.status==='online'?'ONLINE':'OFFLINE'}</span></td></tr>`).join('')}</tbody></table>`;return}$('#statBots').textContent=b.length;$('#statBotsSub').textContent=`${online} online`;$('#statGuilds').textContent=guilds;$('#statCommands').textContent=commands;$('#statHealth').textContent=b.length?Math.round(online/b.length*100)+'%':'—';$('#botGrid').innerHTML=b.length?b.map(botCard).join(''):'<div class="empty-panel glass"><span>🤖</span><h3>No agents connected yet</h3><p>Start a Wispbyte Runner and bot SDK bridge to populate live bot cards.</p></div>';$('#botTable').innerHTML=`<table><thead><tr><th>BOT</th><th>STATUS</th><th>HOST</th><th>PING</th><th>CPU</th><th>RAM</th><th>VERSION</th></tr></thead><tbody>${b.map(x=>`<tr><td><b>${esc(x.name)}</b><br><small>${esc(x.bot_id)}</small></td><td><span class="status-pill ${x.status==='online'?'online':'offline'}">${esc(x.status)}</span></td><td>${esc(x.host_id||'—')}</td><td>${Math.round(x.ping_ms||0)} ms</td><td>${Number(x.cpu||0).toFixed(1)}%</td><td>${Number(x.memory_mb||0).toFixed(1)} MB</td><td>${esc(x.version||'—')}</td></tr>`).join('')}</tbody></table>`;const fill=sel=>{const e=$(sel);if(e)e.innerHTML=b.map(x=>`<option value="${esc(x.bot_id)}">${esc(x.name)} (${esc(x.bot_id)})</option>`).join('')};['#cmdBot','#scheduleBot','#devBot'].forEach(fill);const avgPing=b.length?b.reduce((a,x)=>a+(x.ping_ms||0),0)/b.length:0,ram=b.reduce((a,x)=>a+(x.memory_mb||0),0),cpu=b.length?b.reduce((a,x)=>a+(x.cpu||0),0)/b.length:0;$('#aOnline').textContent=b.length?Math.round(online/b.length*100)+'%':'0%';$('#aPing').textContent=Math.round(avgPing)+'ms';$('#aRam').textContent=Math.round(ram)+'MB';$('#aCpu').textContent=cpu.toFixed(1)+'%';$('#healthBars').innerHTML=b.map(x=>{const score=x.status==='online'?Math.max(5,100-Math.min(95,(x.cpu||0)*.5+(x.ping_ms||0)/8)):2;return `<div class="health-row"><b>${esc(x.name)}</b><div class="bar"><i style="width:${score}%"></i></div><span>${Math.round(score)}%</span></div>`}).join('')}
async function loadBots(){try{state.bots=await api('/api/bots');renderBots();log(`Fleet refreshed: ${state.bots.length} bots`)}catch(e){toast(e.message,true)}}
window.life=async(bot,action)=>{try{toast(`${action} → ${bot}`);const r=await api(`/api/bots/${encodeURIComponent(bot)}/lifecycle`,{method:'POST',body:JSON.stringify({action})});log(`${bot}: ${action} → ${JSON.stringify(r)}`);setTimeout(loadBots,700)}catch(e){toast(e.message,true);log(`ERROR ${e.message}`)}};
async function runCommand(){try{const body={bot_id:$('#cmdBot').value,guild_id:$('#cmdGuild').value.trim(),command:$('#cmdName').value.trim(),args:JSON.parse($('#cmdArgs').value||'{}')};const r=await api('/api/command',{method:'POST',body:JSON.stringify(body)});$('#cmdResult').textContent=JSON.stringify(r,null,2);log(`command ${body.command} on ${body.bot_id}`);toast('Command executed')}catch(e){$('#cmdResult').textContent='ERROR: '+e.message;toast(e.message,true)}}
async function createSchedule(){try{const body={bot_id:$('#scheduleBot').value,guild_id:$('#scheduleGuild').value.trim(),command:$('#scheduleCommand').value.trim(),args:JSON.parse($('#scheduleArgs').value||'{}'),run_at:$('#scheduleAt').value.trim()};const r=await api('/api/schedule',{method:'POST',body:JSON.stringify(body)});toast(`Scheduled job #${r.job_id}`);loadSchedules()}catch(e){toast(e.message,true)}}
async function loadSchedules(){try{const rows=await api('/api/schedule');$('#scheduleList').innerHTML=rows.map(x=>`<div class="schedule-row"><b>#${x.id}</b><span>${esc(x.bot_id)}</span><small>${esc(x.run_at)}</small><span>${esc(x.status)}</span></div>`).join('')||'<p class="muted">No scheduled jobs.</p>'}catch(e){toast(e.message,true)}}
async function loadAudit(){try{const rows=await api('/api/audit');$('#auditList').innerHTML=rows.map(x=>`<div class="audit-row"><small>${new Date(x.created_at).toLocaleString()}</small><b>${esc(x.username)}</b><span>${esc(x.action)}</span><small>${esc(x.target||'')} ${esc(x.detail||'')}</small></div>`).join('')||'<p class="muted">No audit events.</p>'}catch(e){toast(e.message,true)}}
async function loadErrors(){try{const rows=await api('/api/errors');$('#errorList').innerHTML=rows.map(x=>`<div class="error-row"><small>${new Date(x.created_at).toLocaleString()}</small><b>${esc(x.bot_id)}</b><span>${esc(x.message)}</span></div>`).join('')||'<p class="muted">No errors recorded.</p>'}catch(e){toast(e.message,true)}}
async function listScripts(){try{const bot=$('#devBot').value,r=await api(`/api/bots/${encodeURIComponent(bot)}/scripts`);$('#scriptList').innerHTML=(r.files||[]).map(f=>`<button class="file-item" onclick="pickFile('${String(f).replace(/'/g,"\\'")}')">${esc(f)}</button>`).join('')||'<p class="muted">No approved files.</p>'}catch(e){toast(e.message,true)}}
window.pickFile=f=>{$('#scriptPath').value=f;readScript()};
async function readScript(){try{const bot=$('#devBot').value,path=$('#scriptPath').value.trim();const r=await api(`/api/bots/${encodeURIComponent(bot)}/script/read`,{method:'POST',body:JSON.stringify({path})});$('#scriptContent').value=r.content||'';toast('File loaded')}catch(e){toast(e.message,true)}}
async function writeScript(){try{const bot=$('#devBot').value,path=$('#scriptPath').value.trim(),content=$('#scriptContent').value;await api(`/api/bots/${encodeURIComponent(bot)}/script/write`,{method:'POST',body:JSON.stringify({path,content})});toast('File saved');log(`Owner updated ${bot}/${path}`)}catch(e){toast(e.message,true)}}
async function loadServers(){try{const rows=await api('/api/servers');$('#serverList').innerHTML=`<table><thead><tr><th>SERVER</th><th>GUILD ID</th><th>BOT</th><th>MEMBERS</th></tr></thead><tbody>${rows.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td><code>${esc(x.guild_id)}</code></td><td>${esc(x.bot_id)}</td><td>${Number(x.member_count||0).toLocaleString()}</td></tr>`).join('')}</tbody></table>`||'<p class="muted">No servers reported yet.</p>'}catch(e){toast(e.message,true)}}
async function loadLogs(){try{const rows=await api('/api/logs?limit=250');$('#liveLog').textContent=(rows.reverse().map(x=>`[${new Date(x.created_at).toLocaleTimeString()}] [${x.bot_id}] [${x.stream}] ${x.message}`).join('\n'))||'No bot output yet.'}catch(e){toast(e.message,true)}}
function showAuth(msg=''){document.getElementById('dashboardApp').classList.add('hidden-app');document.getElementById('authGate').classList.remove('hidden-auth');const e=document.getElementById('authError');if(msg){e.textContent=msg;e.classList.add('show')}else e.classList.remove('show')}
function showDashboard(){document.getElementById('authGate').classList.add('hidden-auth');document.getElementById('dashboardApp').classList.remove('hidden-app')}
async function exchangeAuthCode(){const hash=new URLSearchParams(location.hash.replace(/^#/,''));const code=hash.get('auth_code');const denied=hash.get('denied');if(denied){history.replaceState(null,'',location.pathname);showAuth(denied==='guild'?'Access denied — you must be a member of the authorized Discord server.':'Access denied — your Discord account does not have an authorized dashboard role.');return false}if(!code)return false;try{const r=await fetch(apiBase()+'/auth/exchange',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code})});const data=await r.json();if(!r.ok)throw new Error(data.detail||'Login exchange failed');sessionStorage.setItem('zbc_token',data.access_token);history.replaceState(null,'',location.pathname);return true}catch(e){history.replaceState(null,'',location.pathname);showAuth(e.message);return false}}
async function logout(){try{if(token())await fetch(apiBase()+'/auth/token/logout',{method:'POST',headers:{Authorization:`Bearer ${token()}`}})}catch{}sessionStorage.removeItem('zbc_token');localStorage.removeItem('zbc_token');state.me=null;showAuth()}
async function init(){document.getElementById('backendLabel').textContent=apiBase()?`Backend: ${apiBase()}`:'Backend not configured';document.getElementById('discordLogin').onclick=()=>{if(!apiBase()||apiBase().includes('YOUR-PANEL'))return showAuth('Open config.js and set your Wispbyte backend URL first.');location.href=apiBase()+'/auth/discord'};await exchangeAuthCode();if(!token()){showAuth();return}try{state.me=await api('/api/me');showDashboard();applyRole();await loadBots();const saved=localStorage.getItem('zbc_view')||'overview';if(state.me.role==='staff')setView('bots');else if(state.me.role==='admin'&&['permissions','developer'].includes(saved))setView('overview');else setView(saved);setInterval(loadBots,15000)}catch(e){sessionStorage.removeItem('zbc_token');showAuth('Session expired. Sign in again.')}}
$$('.nav-item').forEach(b=>b.onclick=()=>setView(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>setView(b.dataset.go));$('#refreshBtn').onclick=loadBots;$('#runCommand').onclick=runCommand;$('#createSchedule').onclick=createSchedule;$('#loadAudit').onclick=loadAudit;$('#loadErrors').onclick=loadErrors;$('#loadServers').onclick=loadServers;$('#loadLogs').onclick=loadLogs;$('#listScripts').onclick=listScripts;$('#readScript').onclick=readScript;$('#writeScript').onclick=writeScript;document.getElementById('logoutBtn').onclick=logout;init();
